name: Deploy SST App

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: merge-${{ github.ref }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ejd-prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::211125708921:role/GithubAction-Build
          role-duration-seconds: 3600
          aws-region: us-east-1

      - name: Install dependencies
        run: npm install

      - name: Deploy SST app to Prod
        run: pnpm sst deploy --stage ejd-prod